// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT0w81pyfR1HXLe7qaf9YtnRjovjY05G4',
    appId: '1:1048232108520:web:0812f967bbff65fab2c45d',
    messagingSenderId: '1048232108520',
    projectId: 'raftconnectapp',
    authDomain: 'raftconnectapp.firebaseapp.com',
    storageBucket: 'raftconnectapp.appspot.com',
    measurementId: 'G-JMRVVN2391',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkrNbTbj-yqK7ZmaJ_W6BHzTF7bQqAQ68',
    appId: '1:1048232108520:android:b9fd4bcd3b9e4f70b2c45d',
    messagingSenderId: '1048232108520',
    projectId: 'raftconnectapp',
    storageBucket: 'raftconnectapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAULGCnSoKubih0VjLBmAHUh6we_XHHBmE',
    appId: '1:1048232108520:ios:e7cd38338b60a352b2c45d',
    messagingSenderId: '1048232108520',
    projectId: 'raftconnectapp',
    storageBucket: 'raftconnectapp.appspot.com',
    iosBundleId: 'com.example.raft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAULGCnSoKubih0VjLBmAHUh6we_XHHBmE',
    appId: '1:1048232108520:ios:727416761d8ada15b2c45d',
    messagingSenderId: '1048232108520',
    projectId: 'raftconnectapp',
    storageBucket: 'raftconnectapp.appspot.com',
    iosBundleId: 'com.example.raft.RunnerTests',
  );
}
